In [96]:
import numpy as np
class LogisticRegression:
    def __init__(self,learning_rate=0.1, epochs = 1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None
        
    def sigmoid(self, X):
        return 1/(1+np.exp(-X))

    def softmax(self, X):
        exp_vals = np.exp(X - np.max(X, axis=1, keepdims=True))  # Avoid numerical instability
        return exp_vals / np.sum(exp_vals, axis=1, keepdims=True)

        
    def fit(self,X,y):
        #X dimensions are m*n 
        #m -> number of instances, n-> features
        n_instances, n_features = X.shape
        self.classes = np.unique(y)
        self.classes_count = len(self.classes)
        if len(self.classes) <= 2:
            self.labels = "binary"
            self.weights =  np.zeros(n_features)
            self.bias = 0
        else:
            self.labels = "multiclass"
            self.weights = np.zeros((n_features,self.classes_count))
            self.bias = np.zeros(self.classes_count)
        
        for _ in range(self.epochs):
            output = np.dot(X,self.weights) + self.bias
            if self.labels == "binary":
                logits = self.sigmoid(output)
                error = logits-y
                dw = np.dot(X.T,error)/ n_instances
                db = np.sum(error, axis=0) / n_instances 
                self.weights -= self.learning_rate * dw
                self.bias -= self.learning_rate * db
                
            
            else:
                logits = self.softmax(output)
                y_one_hot = np.eye(self.classes_count)[y]
                error = logits - y_one_hot
                dw = np.dot(X.T, error)/ n_instances
                db = np.sum(error,axis=0) / n_instances 
                self.weights -= self.learning_rate * dw
                self.bias -= self.learning_rate * db
                
        
    def predict(self,X, threshold = 0.5):
        if self.labels == "binary":
            probs = self.sigmoid(np.dot(X,self.weights) + self.bias)
            return (probs>=threshold).astype(int)
        probs = self.softmax(np.dot(X,self.weights) + self.bias)
        return np.argmax(probs, axis=1)

In [97]:
lr = LogisticRegression()
lr.fit(X,y)


(9, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
(9, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0.28798512 0.33236778 0.3796471 ]
 [0.28784844 0.33243159 0.37971998]
 [0.28812184 0.33230396 0.3795742 ]
 [0.21056513 0.31940557 0.47002929]
 [0.20872444 0.31894381 0.47233175]
 [0.20705818 0.31840787 0.47453395]
 [0.14763419 0.29434058 0.55802523]
 [0.14755032 0.29436954 0.55808014]
 [0.15184365 0.29654077 0.55161558]]
(9, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[

In [98]:
lr.predict(X)

array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64)

In [87]:
import numpy as np
import pandas as pd

# Features (2D points) and labels (3 classes: 0, 1, 2)
data = {
    "x1": [1.0, 1.2, 0.8, 3.0, 3.2, 3.1, 5.0, 5.2, 4.8],
    "x2": [1.1, 0.9, 1.3, 3.1, 3.0, 3.2, 5.1, 4.9, 5.0],
    "label": [0, 0, 0, 1, 1, 1, 2, 2, 2]
}

# Convert to a Pandas DataFrame (optional, for visualization)
df = pd.DataFrame(data)

# Features and labels as NumPy arrays
X = df[["x1", "x2"]].values  # Features
y = df["label"].values        # Labels


In [94]:
y_one_hot = np.eye(3)[y]

In [95]:
y_one_hot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])