In [3]:
#min-max scalar
import numpy as np

In [49]:
class MinMaxScalar:
    def __init__(self,feature_range=(0,1)):
        self.X_max = None
        self.X_min = None
        self.lower_bound = feature_range[0]
        self.upper_bound = feature_range[1]

    def fit(self,X):
        self.X_max = np.max(X,axis=0)
        self.X_min = np.min(X,axis=0) 
        

    def transform(self,X):
        scaled = (X-self.X_min)/(self.X_max-self.X_min)
        return self.lower_bound + scaled*(self.upper_bound-self.lower_bound)

    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)

In [50]:
scalar = MinMaxScalar((2,3))
scalar.fit_transform(X)

array([[2. , 2. , 2.2],
       [2.5, 2.5, 3. ],
       [3. , 3. , 2. ]])

In [48]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler((2,3))

normalized_data = scaler.fit_transform(X)

print(normalized_data)

[[2.  2.  2.2]
 [2.5 2.5 3. ]
 [3.  3.  2. ]]


In [44]:
X

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10,  2]])